#!/bin/bash

EVAL_STRING="let MONGO_USERNAME = '$MONGO_USERNAME', \
MONGO_PASSWORD = '$MONGO_PASSWORD', \
MONGO_INITDB_DATABASE = '$MONGO_INITDB_DATABASE';"

mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --eval "${EVAL_STRING}" /scripts/create_user.js